# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: pipeline .NET

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  publish:
    
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
        contents: read
        packages: write
        
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

  deploy-STG:
    
    runs-on: ubuntu-latest
    needs: publish
    
    environment:
      name: stg

    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy
        shell: bash
        run: |
          echo "Deploy STG"

  deploy-Pre:
    
    runs-on: ubuntu-latest
    needs: publish
    
    environment:
      name: pre

    if: github.ref == 'refs/heads/release'
    steps:
      - name: Deploy
        shell: bash
        run: |
          echo "Deploy PRE"

  deploy-Prod:
    
    runs-on: ubuntu-latest
    needs: publish
    
    environment:
      name: prod

    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
        shell: bash
        run: |
          echo "Deploy PROD"
    
    
   
